### ISSUE TITLE
[EPIC] Introduce same non-quarkus guides as we have for with quarkus

### ISSUE THREAD

**Issue by domhanak** [apache/incubator-kie-kogito-docs#543]
**Summary**
As we are shifting towards more java-less guides we need to introduce such examples
where no Quarkus and Java is exposed to the user.

**Goal**
- [ ] Introduce getting-started-with-events guide for `core/handling-events-on-workflows.adoc`
- [ ] Introduce getting-started-with-callbacks guide for `core/working-with-callbacks.adoc`
- [ ] Update reference to a guides without quarkus for `core/understanding-jq-expressions.adoc`
- [ ] Introduce getting-started-with-inputs for `core/defining-an-input-schema-for-workflows.adoc`
- [ ] Introduce getting-started-with-outputs for `core/defining-an-input-schema-for-workflows.adoc`
- [ ] Review any other guide and ensure we reference non-quarkus examples in non-quarkus section
